// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/analyze-prompt.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
var RATE_LIMIT_PER_MIN = 20;
function admin() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
async function checkRateLimit(userId, toolName) {
  const db = admin();
  const since = new Date(Date.now() - 6e4).toISOString();
  const { count, error } = await db.from("mcp_rate_limits").select("id", { count: "exact", head: true }).eq("user_id", userId).eq("tool_name", toolName).gte("called_at", since);
  if (error) return null;
  if ((count ?? 0) >= RATE_LIMIT_PER_MIN) {
    return `Rate limit exceeded: max ${RATE_LIMIT_PER_MIN} calls/min for ${toolName}. Try again shortly.`;
  }
  await db.from("mcp_rate_limits").insert({ user_id: userId, tool_name: toolName });
  return null;
}
async function logCall(params) {
  try {
    await admin().from("mcp_call_logs").insert({
      user_id: params.userId,
      client_id: params.clientId ?? null,
      tool_name: params.toolName,
      status: params.status,
      duration_ms: params.durationMs,
      error: params.error ?? null,
      input: params.input
    });
  } catch {
  }
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { error: "Authentication required. Sign in to use this tool." };
  }
  return { userId: ctx.getUserId(), clientId: ctx.getClientId() };
}

// src/lib/mcp/tools/analyze-prompt.ts
var analyze_prompt_default = defineTool({
  name: "analyze_video_prompt",
  title: "Analyze video prompt",
  description: "Analyze an Arabic or English video description and return a scene-by-scene shot plan (character, environment, camera moves, actions, narration) suitable for animated video production.",
  inputSchema: {
    prompt: z.string().min(1).describe("The video description to analyze."),
    sceneCount: z.number().int().min(1).max(8).default(4).describe("Number of scenes to plan."),
    type: z.enum(["text-to-video", "image-to-video"]).default("text-to-video").describe("Kind of video generation.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ prompt, sceneCount, type }, ctx) => {
    const started = Date.now();
    const auth = requireAuth(ctx);
    if ("error" in auth) {
      return { content: [{ type: "text", text: auth.error }], isError: true };
    }
    const rl = await checkRateLimit(auth.userId, "analyze_video_prompt");
    if (rl) {
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "rate_limited", durationMs: Date.now() - started, error: rl, input: { prompt, sceneCount, type } });
      return { content: [{ type: "text", text: rl }], isError: true };
    }
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "error", durationMs: Date.now() - started, error: "missing LOVABLE_API_KEY", input: { prompt, sceneCount, type } });
      return {
        content: [{ type: "text", text: "LOVABLE_API_KEY is not configured on the server." }],
        isError: true
      };
    }
    const systemPrompt = `You are a creative AI director for animated video production. Given a user's video description, return a JSON object with:
1. "character": one of "realistic", "cartoon", "fantasy", "none".
2. "environment": one of "animated-nature", "night-city", "space", "underwater", "desert", "forest", "indoor", "school", "park".
3. "scenes": array of ${sceneCount} objects each with description, action (idle|talking|walking|running|fighting|chasing|emotional|dramatic|dancing), camera (static|pan-left|pan-right|zoom-in|zoom-out|shake|dolly|tilt-up|tilt-down|beat-pulse), intensity 0..1, characterDirection (left|right|center).
4. "narrationText": short Arabic narration (2-3 sentences).
Return ONLY valid JSON, no markdown.`;
    try {
      const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `Video description: "${prompt}"
Video type: ${type}` }
          ]
        })
      });
      if (!res.ok) {
        const t = await res.text();
        await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "error", durationMs: Date.now() - started, error: `gateway ${res.status}: ${t.slice(0, 200)}`, input: { prompt, sceneCount, type } });
        return {
          content: [{ type: "text", text: `AI gateway error ${res.status}: ${t}` }],
          isError: true
        };
      }
      const data = await res.json();
      const content = data.choices?.[0]?.message?.content ?? "";
      const jsonStr = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      let parsed;
      try {
        parsed = JSON.parse(jsonStr);
      } catch {
        await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "error", durationMs: Date.now() - started, error: "invalid JSON from model", input: { prompt, sceneCount, type } });
        return {
          content: [{ type: "text", text: content }],
          isError: true
        };
      }
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "success", durationMs: Date.now() - started, input: { prompt, sceneCount, type } });
      return {
        content: [{ type: "text", text: JSON.stringify(parsed, null, 2) }],
        structuredContent: parsed
      };
    } catch (e) {
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "analyze_video_prompt", status: "error", durationMs: Date.now() - started, error: e instanceof Error ? e.message : "unknown", input: { prompt, sceneCount, type } });
      return {
        content: [{ type: "text", text: e instanceof Error ? e.message : "Unknown error" }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/generate-image.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var generate_image_default = defineTool2({
  name: "generate_scene_image",
  title: "Generate scene image",
  description: "Generate a single scene image via Lovable AI (Gemini image models). Returns a data URL for the produced image.",
  inputSchema: {
    prompt: z2.string().min(1).describe("Image description."),
    style: z2.string().optional().describe("Optional art style, e.g. 'cinematic', 'cartoon'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ prompt, style }, ctx) => {
    const started = Date.now();
    const auth = requireAuth(ctx);
    if ("error" in auth) {
      return { content: [{ type: "text", text: auth.error }], isError: true };
    }
    const rl = await checkRateLimit(auth.userId, "generate_scene_image");
    if (rl) {
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "generate_scene_image", status: "rate_limited", durationMs: Date.now() - started, error: rl, input: { prompt, style } });
      return { content: [{ type: "text", text: rl }], isError: true };
    }
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "generate_scene_image", status: "error", durationMs: Date.now() - started, error: "missing LOVABLE_API_KEY", input: { prompt, style } });
      return {
        content: [{ type: "text", text: "LOVABLE_API_KEY is not configured on the server." }],
        isError: true
      };
    }
    const finalPrompt = style && !prompt.toLowerCase().includes(style.toLowerCase()) ? `${prompt}. Art style: ${style}` : prompt;
    const models = [
      "google/gemini-3-pro-image-preview",
      "google/gemini-3.1-flash-image-preview",
      "google/gemini-2.5-flash-image"
    ];
    for (const model of models) {
      try {
        const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
          method: "POST",
          headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model,
            messages: [{ role: "user", content: finalPrompt }],
            modalities: ["image", "text"]
          })
        });
        if (!res.ok) continue;
        const data = await res.json();
        const finishReason = data.choices?.[0]?.native_finish_reason || data.choices?.[0]?.finish_reason;
        const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
        if (finishReason === "IMAGE_SAFETY" || !imageUrl) continue;
        await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "generate_scene_image", status: "success", durationMs: Date.now() - started, input: { prompt, style, model } });
        return {
          content: [{ type: "text", text: imageUrl }],
          structuredContent: { imageUrl, model }
        };
      } catch {
        continue;
      }
    }
    await logCall({ userId: auth.userId, clientId: auth.clientId, toolName: "generate_scene_image", status: "error", durationMs: Date.now() - started, error: "all image models failed", input: { prompt, style } });
    return {
      content: [{ type: "text", text: "Could not generate image. Try a different prompt." }],
      isError: true
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "agon-video-mcp",
  title: "Agon Video Studio MCP",
  version: "0.1.0",
  instructions: "Tools for the Agon animated video studio. Use `analyze_video_prompt` to plan a scene-by-scene shot list from a description, and `generate_scene_image` to render an individual scene image.",
  tools: [analyze_prompt_default, generate_image_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
